# Generated by Django 5.2.16 on 2026-07-16 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estagiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('curso', models.CharField(max_length=200, verbose_name='Curso')),
                ('instituicao', models.CharField(max_length=200, verbose_name='Instituição')),
                ('carga_total', models.DecimalField(decimal_places=1, help_text='Total de horas do estágio', max_digits=6, verbose_name='Carga horária total')),
                ('carga_semanal', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Carga horária semanal')),
                ('inicio', models.DateField(verbose_name='Data de início')),
                ('fim', models.DateField(verbose_name='Data prevista para término')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estagiarios_supervisionados', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estagiario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Estagiário',
                'verbose_name_plural': 'Estagiários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('HOME_OFFICE', 'Home Office')], max_length=20, verbose_name='Tipo')),
                ('data', models.DateField(verbose_name='Data')),
                ('entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada')),
                ('saida', models.TimeField(blank=True, null=True, verbose_name='Hora de saída')),
                ('horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição das atividades')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='APROVADO', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/%Y/%m/', verbose_name='Anexo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estagiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.estagiario', verbose_name='Estagiário')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
